services:
  minio:
    image: minio/minio
    ports:
      - "9100:9000"
      - "9101:9001"
    volumes:
      - minio_data:/export
      - minio_config:/root/.minio
    environment:
      - "MINIO_ROOT_USER=minio"
      - "MINIO_ROOT_PASSWORD=password"
    command: server /export --console-address :9001
  db:
    container_name: portal
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portal
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/15/data

volumes:
  pgdata:
  minio_data:
  minio_config:
