import { GetServerSideProps } from "next";
import Head from "next/head";
import Link from "next/link";
import PageHeader from "@/components/layout/PageHeader";
import { Role } from "@prisma/client";
import { authOptions } from "./api/auth/[...nextauth]";
import { getServerSession } from "next-auth";
import { isEmpty } from "lodash-es";
import prisma from "@/lib/prisma";
import { useSession } from "next-auth/react";

type Props = Record<string, never>;

const allowedRoles: Role[] = [Role.PRACTITIONER, Role.STAFF];

export const getServerSideProps: GetServerSideProps<Props> = async ({
  req,
  res,
}) => {
  const session = await getServerSession(req, res, authOptions);

  const user = await prisma.employee.findUnique({
    where: {
      id: session?.user.id ?? "",
    },
    select: {
      accounts: {
        select: {
          role: true,
          organization: {
            select: {
              id: true,
              billingAddresses: true,
              type: true,
            },
          },
        },
      },
    },
  });

  if (!user) {
    return {
      redirect: {
        destination: "/sign-in",
        permanent: false,
      },
    };
  }

  if (
    user.accounts.length === 1 &&
    isEmpty(user.accounts[0].organization.billingAddresses)
  ) {
    return {
      redirect: {
        destination: `/billing-info`,
        permanent: false,
      },
    };
  }

  if (user.accounts[0].role === Role.BILLING_MANAGER) {
    return {
      redirect: {
        destination: `/billing`,
        permanent: false,
      },
    };
  }

  if (user.accounts[0].organization.type === "RESEARCH") {
    return {
      redirect: {
        destination: `/research/dashboard`,
        permanent: false,
      },
    };
  }

  if (!allowedRoles.includes(user.accounts[0].role)) {
    return {
      redirect: {
        destination: "/404.tsx",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
};

export default function Home() {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Resonant</title>
        <meta name="description" content="Generated by resonant-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full justify-center rounded-md">
        <div className="flex w-full flex-col">
          <PageHeader title={`Welcome, ${session?.user.name}`} />
          <div className="h-2/3 rounded-md p-8">
            <div className="flex h-5/6 flex-col items-center gap-4">
              <div className="shadow-b flex h-1/2 w-full flex-col items-center justify-center rounded-md border border-highlight-600 p-4 shadow-lg shadow-highlight-600">
                <div className="rounded-mdp-4 flex w-full flex-col items-center">
                  <h2 className="text-lg ">TEXT GOES HERE</h2>
                  <p>
                    {
                      "[Tell the patient what we do.] Tell us what you are interested in!"
                    }
                  </p>
                  <p>Let us know what you are looking for</p>
                  <p>Let us know what you are looking for</p>
                  <p>Let us know what you are looking for</p>
                </div>
              </div>
            </div>
          </div>
          <div className=" h-1/3 rounded-md p-8">
            <h2 className="ml-4 mt-4 flex text-xl ">Quick Links</h2>
            <div className="flex w-full flex-col items-center justify-center gap-12 pt-4">
              <div className="grid min-h-32 w-full grid-cols-1 gap-4 md:grid-cols-3">
                <div className="shadow-b flex flex-col items-center justify-center rounded-md border border-highlight-600 p-4 shadow-lg shadow-highlight-600">
                  <h3 className="text-xl ">Resources</h3>
                  <p>{"[Link information]"}</p>
                  <Link
                    className=" text-highlight-600"
                    href="https://www.resonantdx.com/"
                    target="_blank"
                  >
                    Listen Now
                  </Link>
                </div>

                <div className="shadow-b flex flex-col items-center justify-center rounded-md border border-highlight-600 p-4 shadow-lg shadow-highlight-600">
                  <h3 className="text-xl ">Customer Service</h3>
                  <p>{"[Link information]"}</p>
                  <Link
                    className=" text-highlight-600"
                    href="https://www.resonantdx.com/"
                    target="_blank"
                  >
                    Read Now
                  </Link>
                </div>

                <div className="shadow-b flex flex-col items-center justify-center rounded-md border border-highlight-600 p-4 shadow-lg shadow-highlight-600">
                  <h3 className="text-xl ">Lab Reference</h3>
                  <p>{"[Link information]"}</p>
                  <Link
                    className=" text-highlight-600"
                    href="https://www.resonantdx.com/"
                    target="_blank"
                  >
                    Go to Lab Reference
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
