import Head from "next/head";
import PageHeader from "@/components/layout/PageHeader";
import { useSession } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by Portfolio-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full justify-center rounded-md">
        <div className="flex w-full flex-col">
          <PageHeader title={`Welcome, ${session?.user.name}`} />
          <div className="h-2/3 rounded-md p-8">
            <div className="flex h-5/6 flex-col items-center gap-4">
              <div className="shadow-b flex h-1/2 w-full flex-col items-center justify-center rounded-md border border-highlight-600 p-4 shadow-lg shadow-highlight-600">
                <div className="rounded-mdp-4 flex w-full flex-col items-center">
                  <h2 className="text-lg ">TEXT GOES HERE</h2>
                  <p>
                    {
                      "[Tell the patient what we do.] Tell us what you are interested in!"
                    }
                  </p>
                  <p>Let us know what you are looking for</p>
                  <p>Let us know what you are looking for</p>
                  <p>Let us know what you are looking for</p>
                </div>
              </div>
            </div>
          </div>
          <div className=" h-1/3 rounded-md p-8">
            <h2 className="ml-4 mt-4 flex text-xl ">Quick Links</h2>
            <div className="flex w-full flex-col items-center justify-center gap-12 pt-4">
              <div className="grid min-h-32 w-full grid-cols-1 gap-4 md:grid-cols-3">
                <div className="shadow-b flex flex-col items-center justify-center rounded-md border border-highlight-600 p-4 shadow-lg shadow-highlight-600">
                  <h3 className="text-xl ">Resources</h3>
                </div>

                <div className="shadow-b flex flex-col items-center justify-center rounded-md border border-highlight-600 p-4 shadow-lg shadow-highlight-600">
                  <h3 className="text-xl ">Customer Service</h3>
                </div>

                <div className="shadow-b flex flex-col items-center justify-center rounded-md border border-highlight-600 p-4 shadow-lg shadow-highlight-600">
                  <h3 className="text-xl ">Lab Reference</h3>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
