name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.19]
    env:
      NODE_ENV: "test"
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup node env 🏗
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Cache node_modules 📦
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Linting check
        run: pnpm run lint

      - name: Building application
        run: pnpm run build:ci

      - name: Type Check
        run: pnpm exec tsc --noEmit

      - name: Test
        run: pnpm test
